CREATE DOMAIN TEXT100 AS VARCHAR(100);
CREATE DOMAIN TEXT255 AS VARCHAR(255);
CREATE DOMAIN D_EMAIL AS VARCHAR(150);
CREATE DOMAIN D_ROL AS VARCHAR(50)
CHECK (VALUE IN ('ADMIN', 'ESTUDIANTE', 'DOCENTE'));

CREATE DOMAIN D_ESTADO_AS AS VARCHAR(50)
CHECK (VALUE IN ('PRESENTE', 'AUSENTE', 'RETRASO'));

CREATE TABLE usuarios(
    id SERIAL PRIMARY KEY,
    nombre TEXT100 NOT NULL,
    apellido TEXT100 NOT NULL,
    cedula TEXT100 UNIQUE NOT NULL,
    email D_EMAIL NOT NULL,
    username TEXT100 UNIQUE NOT NULL,
    password_hash TEXT255 NOT NULL,
    rol D_ROL NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE estudiantes(
    id SERIAL PRIMARY KEY,
    matricula TEXT100 NOT NULL,
    id_usuario INTEGER NOT NULL REFERENCES usuarios(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE docentes(
    id SERIAL PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuarios(id),
    materia TEXT100 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rostros(
    id SERIAL PRIMARY KEY,
    id_estudiante INTEGER NOT NULL REFERENCES estudiantes(id),
    image_path TEXT255 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE asistencias(
    id SERIAL PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuarios(id),
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    estado D_ESTADO_AS NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
